import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-20`}
      >
        <div className="flex items-center gap-6">
          <Link href={'/'}>LOGO</Link>
          <Link href={'/'}>Home</Link>
          <Link href={'/blog'}>Blog</Link>
          <Link href={'/content'}>Content</Link>

        </div>
        {children}
      </body>
    </html>
  );
}
